language: node_js
node_js:
  - "6.9.2"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm install grunt-cli -g
  - npm install typescript -g
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm -v
